# encoding: utf-8
# vim: ft=ruby expandtab shiftwidth=2 tabstop=2

#
# Network Settings
#
hostname: 2020.ogijima.wordcamp.test
ip: 192.168.20.19

#
# WordPress Settings
#
version: latest
lang: ja
title: Development - WordCamp Ogijima 2020
rewrite_structure: /%postname%/


#
# WordPress User
#
admin_user: wcogijima2020
admin_pass: wcogijima2020
admin_email: wcogijima2020@wordcamp.test

#
# WordPress Default Plugins
# Plugin's slug or url to the plugin's slug.
#
plugins: [
  camptix-pagseguro
  camptix-payfast-gateway
  jetpack
  wordpress-importer
  tagregator
]

#
# WordPress Default Theme
# Theme's slug or url to the theme's .zip.
#
theme: 'twentytwenty'

#
# WordPress Options
#
options:
  blogdescription: 'Hallo, WordCamp ogijima 2020!!'

#
# Theme unit testing
#
theme_unit_test: false
theme_unit_test_uri: https://raw.githubusercontent.com/jawordpressorg/theme-test-data-ja/master/wordpress-theme-test-date-ja.xml

#
# DB will be reset when provision
#
reset_db_on_provision: true

#
# RubyGems
# Wordmove will be forcibly installed.
#
ruby_gems: []

mailcatcher: false

wp_i18n_tools: true

#
# NPM modules
#
npms: []

#
# composer
#
composers: []

#
# wp-cli package commands
#
wp_cli_packages: []

#
# Linked Clone for Vagrant v1.8
#
linked_clone: true
